module.exports = Object.freeze({
  useTabs: false,
  tabWidth: 2,
  expandUsers: false,
  keyOrder: [
    '$schema',
    'name',
    'version',
    'private',
    'description',
    'main',
    'browser',
    'types',
    'files',
    'bin',
    'scripts',
    'repository',
    'keywords',
    'author',
    'contributors',
    'license',
    'bugs',
    'homepage',
    'man',
    'directories',
    'config',
    'dependencies',
    'devDependencies',
    'peerDependencies',
    'bundledDependencies',
    'optionalDependencies',
    'engines',
    'os',
    'cpu',
    'publishConfig',
    'workspaces'
  ]
});
